const puzzleData = {
	PUZZLE_ID: "00",
	SIZE: 10,
	MIN_WORD_LENGTH: 2,

	BLACK_FIELDS: [
		[0, 0],
		[0, 1],
		[0, 8],
		[0, 9],
		[1, 0],
		[1, 1],
		[1, 4],
		[1, 5],
		[1, 8],
		[1, 9],
		[2, 3],
		[2, 6],
		[3, 1],
		[3, 3],
		[3, 4],
		[3, 5],
		[3, 6],
		[3, 8],

		[4, 1],
		[4, 3],
		[4, 6],
		[4, 8],

		[5, 1],
		[5, 3],
		[5, 6],
		[5, 8],

		[6, 2],
		[6, 3],
		[6, 4],
		[6, 5],
		[6, 6],
		[6, 7],

		[8, 0],
		[8, 1],
		[8, 3],
		[8, 4],
		[8, 5],
		[8, 6],
		[8, 8],
		[8, 9],
		[9, 0],
		[9, 1],

		[9, 8],
		[9, 9],
	],

	CLUES: {
		WAAGERECHT: {
			1: {
				c: "Spontaner Zusammenbruch: Der ... brachten ihn ...",
				l: "6",
				s: "ZUFALL",
			},
			5: { c: "Anredlich männlich", l: "2", s: "ER" },
			6: { c: "Dreifach Ausruf des Erstaunens", l: "2", s: "EI" },
			7: {
				c: "Die Konsole steuerte zum bewegten Spiel bei",
				l: "3",
				s: "WII",
			},
			8: { c: "Wissen macht so", l: "2", s: "AH" },
			9: {
				c: "Den um den: wie Schritt für Schritt mit Dampfantrieb",
				l: "3",
				s: "ZUG",
			},
			11: {
				c: "Ja (ital.), doch (fran.) oder Studiengruppe (info.)",
				l: "2",
				s: "SI",
			},
			13: {
				c: "Kommt wiederholt in Meditation vor, gesprochen und auf Yogi-Merch",
				l: "2",
				s: "OM",
			},
			14: { c: "Gehört zu hier wie wann zu dann", l: "2", s: "DA" },
			16: { c: "Mich nennt man so anderswo", l: "2", s: "ME" },
			17: { c: "Der job von 20 waagerecht", l: "10", s: "ENCRYPTION" },
			20: {
				c: "Die Maschine gab alliierten Codebreakern Rätsel auf",
				l: "6",
				s: "ENIGMA",
			},
		},
		SENKRECHT: {
			1: {
				c: "Manches geht nervig auf ihn, der unablässig im Kreis laufende",
				l: "6",
				s: "ZEIGER",
			},
			2: { c: "Vorm Opa noch älter", l: "2", s: "UR" },
			3: { c: "Der in Spanien ist kurze Bach-Stadt", l: "2", s: "LE" },
			4: {
				c: "Mit Verlaub: James hatte die zum Töten",
				l: "6",
				s: "LIZENZ",
			},
			7: {
				c: "Jeder Mensch ... zustimmen: die ist unantastbar",
				l: "6",
				s: "WUERDE",
			},
			10: { c: "Exklusiv für die Harten", l: "6", s: "GARTEN" },
			11: {
				c: "Richtet den Kartenblick nach unten rechts",
				l: "2",
				s: "SO",
			},
			12: { c: "Vorm Biss steht die Bude ", l: "2", s: "IM" },
			15: {
				c: "Hängt man das ... Capitale dran, liest es sich viel länger",
				l: "2",
				s: "AN",
			},
			16: { c: "Beide Hälften vom Kind Ende-Roman", l: "2", s: "MO" },
			18: {
				c: "Spitzname vom ikonischen Freiheitskämpfer",
				l: "3",
				s: "CHE",
			},
			19: { c: "Bei Palästina reiht sie sich ein", l: "3", s: "INA" },
		},
	},
};
