const puzzleData = {
	PUZZLE_ID: "04",
	SIZE: 10,
	MIN_WORD_LENGTH: 3,
	BLACK_FIELDS: [
		[0, 4],
		[0, 5],
		[1, 1],
		[1, 3],
		[1, 6],
		[1, 8],
		[2, 1],
		[2, 8],
		[3, 3],
		[3, 6],
		[4, 1],
		[4, 8],
		[5, 0],
		[5, 9],
		[6, 1],
		[6, 3],
		[6, 6],
		[6, 8],
		[8, 1],
		[8, 2],
		[8, 4],
		[8, 5],
		[8, 7],
		[8, 8],
	],
	CLUES: {
		WAAGERECHT: {
			1: { c: "Das verbindet, die musiziert", l: "4", s: "BAND" },
			3: {
				c: "Hochschulnamensgebendes Gemäuer auf dem Giebichenstein",
				l: "4",
				s: "BURG",
			},
			6: { c: "Notiert einen starken Ton", l: "2", s: "FZ" },
			8: {
				c: "Es ist gleich falsch, Allen oder Keinem zu ... (Seneca)",
				l: "6",
				s: "TRAUEN",
			},
			9: {
				c: "Geschäftlicher Spitzname z.B. nach der Show",
				l: "3",
				s: "BIZ",
			},
			10: {
				c: "Kürzel für die Realität aus der Brille",
				l: "2",
				s: "VR",
			},
			11: { c: "", l: "3", s: "ORT" },
			12: {
				c: "Für die sind ein Bart schon ein großer Wald",
				l: "6",
				s: "LAEUSE",
			},
			15: { c: "", l: "8", s: "BOULETTE" },
			17: { c: "", l: "2", s: "AC" },
			19: {
				c: "Entschleunigt die Kugel auf der langen Bahn? Geometrisches Bauteil in Kfz-Anhalter",
				l: "10",
				s: "BREMSKEGEL",
			},
			22: {
				c: "Anders als sein Butter-Pendant ohne extra Zucker aufm Marmeladenbrot",
				l: "10",
				s: "ERDNUSSMUS",
			},
		},
		SENKRECHT: {
			1: {
				c: "Waisenkitz aus dramatischem Kinderfilm",
				l: "5",
				s: "BAMBI",
			},
			2: {
				c: "Sind keine Nieten in der Gebrauchslotterie? Die Ohne-Zwecks!",
				l: "8",
				s: "NUTZLOSE",
			},
			4: { c: "", l: "8", s: "UNNOETIG" },
			5: {
				c: "Die Frau hat was anderes im Kopf als Minos' Land",
				l: "5",
				s: "GRETA",
			},
			6: {
				c: "In Brasiliens Marginalen informell gesiedelt",
				l: "7",
				s: "FAVELAS",
			},
			7: { c: "Richtungsweisend für Heimkehrende", l: "7", s: "ZURUECK" },
			13: {
				c: "Schmerz-Ausruf: Nimmt vor Fragen erhöhte Position ein",
				l: "2",
				s: "AU",
			},
			14: {
				c: "Macht Pauli zur Heiligen oder Quartier",
				l: "2",
				s: "ST",
			},
			16: { c: "Bei Zeiten der Rückzug der Meere", l: "4", s: "EBBE" },
			18: {
				c: "Summa summarum positiv: Die mit den Kleinen Preisen",
				l: "4",
				s: "PLUS",
			},
			20: {
				c: "Dieser Tag ist verhasst, diese Tage aufbauend",
				l: "3",
				s: "MON",
			},
			21: {
				c: "Die Kugel für den Sommer, den Zapfen für den Winter",
				l: "3",
				s: "EIS",
			},
		},
	},
};
