const puzzleData = {
	PUZZLE_ID: "09",
	SIZE: 10,
	MIN_WORD_LENGTH: 3,

	BLACK_FIELDS: [
		[2, 4],
		[2, 5],
		[4, 0],
		[4, 1],
		[4, 4],
		[4, 5],
		[4, 8],
		[4, 9],
		[5, 2],
		[5, 4],
		[5, 5],
		[5, 7],
		[8, 4],
		[8, 5],
		[9, 4],
		[9, 5],
	],
	CLUES: {
		WAAGERECHT: {
			1: { c: "Windmacher", l: "10", s: "VENTILATOR" },
			9: {
				c: "Ihre Sippe misst mindestens vier Generationen",
				l: "10",
				s: "URGROSSOMA",
			},
			10: {
				c: "Dem Pa hinterher wird's betaubendes Getränk",
				l: "4",
				s: "LOMA",
			},
			11: { c: "", l: "4", s: "TWEN" },
			12: { c: "", l: "10", s: "GRAVIEREND" },

			17: {
				c: "Achtbar, weil achtsam: Nicht nur Rundum-Augen-Sache",
				l: "10",
				s: "RUECKSICHT",
			},
			20: {
				c: "Seine Liebhaber*innen wissen die Arbeit von Spießern zu schätzen",
				l: "10",
				s: "SCHASCHLIK",
			},
			21: { c: "", l: "4", s: "CHER" },
			22: { c: "", l: "4", s: "RILI" },
			23: { c: "", l: "4", s: "HERD" },
			24: { c: "", l: "4", s: "EPOS" },
		},
		SENKRECHT: {
			1: { c: "Obszön abgekürzt", l: "", s: "VULG" },
			2: { c: "Fehler im Fehler", l: "", s: "EROR" },
			3: {
				c: "Nigeria-Kürzel vereint mit landessprachiger Karte",
				l: "",
				s: "NGMAP",
			},
			4: {
				c: "Damit fährt mach gut im Londoner Untergrund",
				l: "10",
				s: "TRAVELCARD",
			},
			5: {
				c: "Zwei Wörter im Lindgren-Lückentext: „In Vimmerby hat ... Kindheit verbracht“",
				l: "",
				s: "ASTRIDIHRE",
			},
			6: { c: "", l: "", s: "TOWER" },
			7: { c: "", l: "", s: "OMEN" },
			8: { c: "", l: "", s: "RAND" },
			13: { c: "", l: "", s: "ARSCH" },
			14: { c: "", l: "", s: "SUCHE" },

			15: { c: "", l: "", s: "PHILO" },
			16: { c: "", l: "", s: "ATKIS" },
			18: { c: "", l: "", s: "EHER" },
			19: { c: "", l: "", s: "CLIP" },
		},
	},
};
