const puzzleData = {
	PUZZLE_ID: "00",
	SIZE: 10,
	MIN_WORD_LENGTH: 2,

	BLACK_FIELDS: [
		[0, 0],
		[0, 1],
		[0, 8],
		[0, 9],
		[1, 0],
		[1, 1],
		[1, 4],
		[1, 5],
		[1, 8],
		[1, 9],
		[2, 3],
		[2, 6],
		[3, 1],
		[3, 3],
		[3, 4],
		[3, 5],
		[3, 6],
		[3, 8],

		[4, 1],
		[4, 3],
		[4, 6],
		[4, 8],

		[5, 1],
		[5, 3],
		[5, 6],
		[5, 8],

		[6, 2],
		[6, 3],
		[6, 4],
		[6, 5],
		[6, 6],
		[6, 7],

		[8, 0],
		[8, 1],
		[8, 3],
		[8, 4],
		[8, 5],
		[8, 6],
		[8, 8],
		[8, 9],
		[9, 0],
		[9, 1],

		[9, 8],
		[9, 9],
	],

	CLUES: {
		WAAGERECHT: {
			1: {
				c: "Spontaner Zusammenbruch: Der ... brachten ihn ...",
				l: "6",
				s: "ZUFALL",
			},
			5: { c: "Anredlich männlich", l: "2", s: "ER" },
			6: { c: "", l: "2", s: "EI" },
			7: {
				c: "Die Konsole steuerte zum bewegten Spiel bei",
				l: "3",
				s: "WII",
			},
			8: { c: "Wissen macht so", l: "2", s: "AH" },
			9: { c: "", l: "3", s: "ZUG" },
			11: { c: "", l: "2", s: "SI" },
			13: { c: "", l: "2", s: "OM" },
			14: { c: "", l: "2", s: "DA" },
			16: { c: "", l: "2", s: "ME" },
			17: { c: "", l: "10", s: "ENCRYPTION" },
			20: { c: "", l: "6", s: "ENIGMA" },
		},
		SENKRECHT: {
			1: { c: "", l: "6", s: "ZEIGER" },
			2: { c: "", l: "2", s: "UR" },
			3: { c: "", l: "2", s: "LE" },
			4: { c: "", l: "6", s: "LIZENZ" },
			7: { c: "", l: "6", s: "WUERDE" },
			10: { c: "", l: "6", s: "GARTEN" },
			11: { c: "", l: "2", s: "SO" },
			12: { c: "", l: "2", s: "IM" },
			15: { c: "", l: "2", s: "AN" },
			16: { c: "", l: "2", s: "MO" },
			18: { c: "", l: "3", s: "CHE" },
			19: { c: "", l: "3", s: "INA" },
		},
	},
};
