const puzzleData = {
	PUZZLE_ID: "04",
	SIZE: 10,
	MIN_WORD_LENGTH: 3,
	BLACK_FIELDS: [
		[0, 4],
		[0, 5],
		[1, 1],
		[1, 3],
		[1, 6],
		[1, 8],
		[2, 1],
		[2, 8],
		[3, 3],
		[3, 6],
		[4, 1],
		[4, 8],
		[5, 0],
		[5, 9],
		[6, 1],
		[6, 3],
		[6, 6],
		[6, 8],
		[8, 1],
		[8, 2],
		[8, 4],
		[8, 5],
		[8, 7],
		[8, 8],
	],
	CLUES: {
		WAAGERECHT: {
			1: { c: "Das verbindet, die musiziert", l: "4", s: "BAND" },
			3: {
				c: "Hochschulnamensgebendes Gemäuer auf dem Giebichenstein",
				l: "4",
				s: "BURG",
			},
			8: {
				c: "„Es ist gleich falsch, \nAllen oder Keinem zu ...“ (Seneca)",
				l: "6",
				s: "TRAUEN",
			},
			9: {
				c: "Geschäftlicher Spitzname \nz.B. nach der Show",
				l: "3",
				s: "BIZ",
			},
			10: { c: "Der Platz am Ende jeder Antwort", l: "3", s: "ORT" },
			11: {
				c: "Für die sind ein Bart schon ein großer Wald",
				l: "6",
				s: "LAEUSE",
			},
			12: {
				c: "Das Kügelchen ist nämlich weit über die Grenzen Frankreichs hinaus bekannt",
				l: "8",
				s: "BOULETTE",
			},
			15: {
				c: "Entschleunigt die Kugel auf der langen Bahn? Geometrisches Bauteil in Kfz-Anhalter",
				l: "10",
				s: "BREMSKEGEL",
			},
			18: {
				c: "Anders als sein Butter-Pendant ohne extra Zucker aufm Marmeladenbrot",
				l: "10",
				s: "ERDNUSSMUS",
			},
		},
		SENKRECHT: {
			1: {
				c: "Waisenkitz aus \ndramatischem Kinderfilm",
				l: "5",
				s: "BAMBI",
			},
			2: {
				c: "Sind keine Nieten in der Gebrauchslotterie? \nDie Ohne-Zwecks!",
				l: "8",
				s: "NUTZLOSE",
			},
			4: {
				c: "„Dass in der Kirche gepredigt wird, macht deswegen die Blitzableiter auf ihnen nicht ...“ (Lichtenberg)",
				l: "8",
				s: "UNNOETIG",
			},
			5: {
				c: "Schwedischer Star der \nFreitags-Futurist*innen",
				l: "5",
				s: "GRETA",
			},
			6: {
				c: "In Brasiliens Marginalen \ninformell gesiedelt",
				l: "7",
				s: "FAVELAS",
			},
			7: { c: "Richtungsweisend für Heimkehrende", l: "7", s: "ZURUECK" },
			13: { c: "Bei Zeiten der Rückzug der Meere", l: "4", s: "EBBE" },
			14: {
				c: "Summa summarum positiv: Die mit den kleinen Preisen",
				l: "4",
				s: "PLUS",
			},
			16: {
				c: "Dieser Tag ist verhasst, \ndiese Tage aufbauend",
				l: "3",
				s: "MON",
			},
			17: {
				c: "Die Kugel für den Sommer, \nden Zapfen für den Winter",
				l: "3",
				s: "EIS",
			},
		},
	},
};
