const puzzleData = {
	PUZZLE_ID: "05",
	SIZE: 10,
	MIN_WORD_LENGTH: 2,
	BLACK_FIELDS: [
		[0, 4],
		[0, 5],
		[2, 1],
		[2, 8],
		[4, 3],
		[4, 6],
		[5, 0],
		[5, 9],
		[6, 4],
		[6, 5],
		[8, 2],
		[8, 7],
	],
	CLUES: {
		WAAGERECHT: {
			1: { c: "", l: "", s: "SABE" },
			5: { c: "", l: "", s: "LACH" },
			9: { c: "", l: "", s: "TRAGEKASSE" },
			12: { c: "", l: "", s: "CALAIS" },
			13: { c: "", l: "", s: "STILLLEBEN" },
			16: { c: "", l: "", s: "SIL" },
			17: { c: "", l: "", s: "EI" },
			18: { c: "", l: "", s: "URI" },
			19: { c: "", l: "", s: "PLANFILM" },
			22: { c: "", l: "", s: "OPUS" },
			23: { c: "", l: "", s: "BLAA" },
			25: { c: "", l: "", s: "GESCHMAEHT" },
			28: { c: "", l: "", s: "LL" },
			29: { c: "", l: "", s: "HEIN" },
			30: { c: "", l: "", s: "NZ" },
			31: { c: "", l: "", s: "UNBEWUSSTE" },
		},
		SENKRECHT: {
			1: { c: "", l: "", s: "STUSS" },
			2: { c: "", l: "", s: "AR" },
			3: { c: "", l: "", s: "BACILLUS" },
			4: { c: "", l: "", s: "EGAL" },
			5: { c: "", l: "", s: "LAIE" },
			6: { c: "", l: "", s: "ASSBULLE" },
			7: { c: "", l: "", s: "CS" },
			8: { c: "", l: "", s: "HENNI" },
			10: { c: "", l: "", s: "ELLEN" },
			11: { c: "", l: "", s: "KALIF" },
			14: { c: "", l: "", s: "TIPPELN" },
			15: { c: "", l: "", s: "ERMAHNT" },
			20: { c: "", l: "", s: "ASCHE" },
			21: { c: "", l: "", s: "IBANS" },
			22: { c: "", l: "", s: "OGLU" },
			24: { c: "", l: "", s: "ATZE" },
			26: { c: "", l: "", s: "HEW" },
			27: { c: "", l: "", s: "MIU" },
		},
	},
};
