const puzzleData = {
	PUZZLE_ID: "05",
	SIZE: 10,
	MIN_WORD_LENGTH: 2,
	BLACK_FIELDS: [
		[0, 4],
		[0, 5],
		[2, 1],
		[2, 8],
		[4, 3],
		[4, 6],
		[5, 0],
		[5, 9],
		[6, 4],
		[6, 5],
		[8, 2],
		[8, 7],
	],
	CLUES: {
		WAAGERECHT: {
			1: {
				c: "Der*die Spanier*in weiß: Padmes engste Vertraute",
				l: "4",
				s: "SABE",
			},
			5: {
				c: "Macht einen Tiroler Schlenker auf seiner Vorarlberg-bis-Bayern-Reise",
				l: "4",
				s: "LECH",
			},
			9: { c: "", l: "10", s: "TRAGEKASSE" },
			12: { c: "", l: "6", s: "CALAIS" },
			13: {
				c: "Stumm druch die Welt? Regungsloses Motiv!",
				l: "10",
				s: "STILLLEBEN",
			},
			16: { c: "Wortteil vom Wortteil", l: "3", s: "SIL" },
			17: { c: "Anwärter auf den War-zuerst-da-Titel", l: "2", s: "EI" },
			18: { c: "", l: "3", s: "URI" },
			19: { c: "", l: "8", s: "PLANFILM" },
			22: { c: "Deren ... besingt das Life", l: "4", s: "OPUS" },
			23: { c: "", l: "4", s: "BLAA" },
			25: { c: "", l: "10", s: "GESCHMAEHT" },
			28: { c: "", l: "2", s: "LL" },
			29: {
				c: "Sein Käpt'n erzählt ihm das Blaue vom Himmel: Blöder Dösbaddel",
				l: "4",
				s: "HEIN",
			},
			30: {
				c: "Egal ob Aukland oder Wellington, stets kurz hinterm dot",
				l: "2",
				s: "NZ",
			},
			31: { c: "", l: "", s: "UNBEWUSSTE" },
		},
		SENKRECHT: {
			1: { c: "So ein Unfug, Humbug, Mumpitz!", l: "5", s: "STUSS" },
			2: { c: "Kurz die Realität erweitert", l: "2", s: "AR" },
			3: { c: "", l: "8", s: "BACILLUS" },
			4: {
				c: "Wer zu den Aktualitäten des Tages mit den Acheln zuckt, dem ist die Aufwärts abwärts",
				l: "4",
				s: "EGAL",
			},
			5: { c: "", l: "4", s: "LAIE" },
			6: {
				c: "Nahrungsstier in umgestelltem Blueless",
				l: "8",
				s: "ESSBULLE",
			},
			7: { c: "", l: "2", s: "CS" },
			8: { c: "", l: "5", s: "HENNI" },
			10: {
				c: "Gehört zu den Frauennamen, jeder hat sie in den Armen",
				l: "5",
				s: "ELLEN",
			},
			11: { c: "", l: "", s: "KALIF" },
			14: { c: "", l: "", s: "TIPPELN" },
			15: { c: "", l: "", s: "ERMAHNT" },
			20: { c: "Kommt in den Becher oder Börse", l: "5", s: "ASCHE" },
			21: { c: "", l: "", s: "IBANS" },
			22: { c: "", l: "", s: "OGLU" },
			24: { c: "", l: "", s: "ATZE" },
			26: { c: "", l: "", s: "HEW" },
			27: { c: "", l: "", s: "MIU" },
		},
	},
};
