const puzzleData = {
	PUZZLE_ID: "10",
	SIZE: 11,
	MIN_WORD_LENGTH: 2,
	BLACK_FIELDS: [
		[0, 10],
		[1, 1],
		[1, 3],
		[1, 5],
		[1, 7],
		[1, 9],
		[2, 5],
		[3, 1],
		[3, 3],
		[3, 5],
		[3, 7],
		[3, 9],
		[4, 0],
		[4, 6],
		[5, 1],
		[5, 3],
		[5, 5],
		[5, 7],
		[5, 9],
		[6, 4],
		[6, 10],
		[7, 1],
		[7, 3],
		[7, 5],
		[7, 7],
		[7, 9],
		[8, 5],
		[9, 1],
		[9, 3],
		[9, 5],
		[9, 7],
		[9, 9],
		[10, 0],
	],
	CLUES: {
		WAAGERECHT: {
			1: {
				c: "Fluten das Postfach, zu Werbezwecken oder Nischeninteressen",
				l: "10",
				s: "NEWSLETTER",
			},
			7: { c: "Ein Megagramm", l: "5", s: "TONNE" },
			8: { c: "Die Hinweise sind aus meiner", l: "5", s: "FEDER" },
			9: {
				c: "Kartenspiel mit schöner sieben \nzu deutsch",
				l: "5",
				s: "BESEN",
			},
			10: {
				c: "Wenn die Software noch \nnicht ganz fertig ist",
				l: "4",
				s: "BETA",
			},
			13: {
				c: "Ist bei Ouzo, Sambuca und Pastis in geselliger Runde dabei",
				l: "4",
				s: "RAKI",
			},
			14: {
				c: "Kürzt die Vorbereitung \nzum Druck ausüben ab",
				l: "5",
				s: "REPRO",
			},
			17: {
				c: "Das Letzte was Fechter*innen \nzu hören bekommen",
				l: "5",
				s: "GARDE",
			},
			18: { c: "Massiv am Cruisen damals", l: "5", s: "TOENE" },
			19: {
				c: "Vorm Tag am See – checkt ihr?",
				l: "10",
				s: "REGENRADAR",
			},
		},
		SENKRECHT: {
			1: {
				c: "Ich bekomme hoffentlich \ndie beste hierfür",
				l: "4",
				s: "NOTE",
			},
			2: { c: "Führt hoch und runter", l: "11", s: "WANDERKARTE" },
			3: {
				c: "Wenn 18 waagerecht künstlerische Einheiten bilden",
				l: "6",
				s: "LIEDER",
			},
			4: {
				c: "Top in Fotografie-Feld: \nSteht für Verlustfreiheit",
				l: "4",
				s: "TIFF",
			},
			5: {
				c: "Elias Forschungsgebiet: Da pflückt es sich gerne ganz von selbst",
				l: "11",
				s: "ERDBEERFELD",
			},
			6: { c: "Gehört methodisch zum error", l: "5", s: "TRIAL" },
			11: { c: "Hat der Hydrogeologe intus", l: "5", s: "DROGE" },
			12: { c: "So eine scharfe Grafik", l: "6", s: "VEKTOR" },
			15: { c: "Virales Internetphänomen", l: "4", s: "MEME" },
			16: {
				c: "Gilt es beim Tasten vor Lücken zu drücken",
				l: "4",
				s: "LEER",
			},
		},
	},
};
