const puzzleData = {
	PUZZLE_ID: "1",
	SIZE: 10,
	BLACK_FIELDS: [
		[0, 0],
		[0, 2],
		[0, 7],
		[0, 9],

		[2, 2],
		[2, 7],
		[3, 1],
		[3, 8],
		[4, 4],
		[4, 5],
		[5, 0],
		[5, 4],
		[5, 5],
		[5, 9],

		[7, 0],
		[7, 2],
		[7, 7],
		[7, 9],
		[8, 3],
		[8, 6],
		[9, 0],
		[9, 4],
		[9, 5],
		[9, 9],
	],
	CLUES: {
		WAAGERECHT: {
			1: { c: "", l: "5", s: "SILBE" },
			5: { c: "", l: "5", s: "ASCII" },
			8: { c: "", l: "7", s: "ERBAUTE" },
			9: { c: "", l: "5", s: "RADIO" },
			11: { c: "", l: "5", s: "TALER" },
			14: { c: "", l: "11", s: "BLOCKCHAINS" },
			16: { c: "", l: "4", s: "GURK" },
			17: { c: "", l: "4", s: "TEKK" },
			18: { c: "", l: "5", s: "FEEDS" },
			19: { c: "", l: "4", s: "PETO" },
			21: { c: "", l: "4", s: "FELL" },
			24: { c: "", l: "11", s: "SCHRUMPELIG" },
			27: { c: "", l: "5", s: "THEMA" },
			28: { c: "", l: "5", s: "LIANE" },
			29: { c: "", l: "7", s: "KARTONS" },
			30: { c: "", l: "5", s: "DUETT" },
			31: { c: "", l: "5", s: "TETRA" },
		},
		SENKRECHT: {
			2: { c: "", l: "5", s: "LEDOR" },
			3: { c: "", l: "11", s: "BRICKFORMAT" },
			4: { c: "", l: "1,3", s: "EBOK" },
			5: { c: "", l: "4", s: "AUTH" },
			6: { c: "", l: "11", s: "STAATSFEINE" },
			7: { c: "", l: "5", s: "CELIE" },
			9: { c: "", l: "3", s: "RBG" },
			10: { c: "", l: "3,4", s: "ALUTECH" },
			12: { c: "", l: "7", s: "ENKELIN" },
			13: { c: "", l: "3", s: "RSK" },
			15: { c: "", l: "5", s: "CREAM" },
			19: { c: "", l: "3", s: "PST" },
			20: { c: "", l: "5", s: "THEKE" },
			22: { c: "", l: "5", s: "ELAST" },
			23: { c: "", l: "3", s: "LGE" },
			25: { c: "", l: "4", s: "UART" },
			26: { c: "", l: "4", s: "PLOT" },
		},
	},
};
